version: '3'

services:
  nginx:
    build:
      context: './nginx'
    volumes:
      - ${WEB_ROOT}:/var/www/html
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    tty: true
    restart: always

  php-cli:
    build:
      context: './php-cli'
    volumes:
      - ${WEB_ROOT}:/var/www/html
    expose:
      - "12360"
    ports:
      - "23461:23460"
    depends_on:
      - mysql
    tty: true
    restart: always

  php-fpm:
    build:
      context: './php-fpm'
    volumes:
      - ${WEB_ROOT}:/var/www/html
    expose:
      - "9000"
    depends_on:
      - mysql
    restart: always
    stdin_open: true
    tty: true
    cap_add:
      - ALL

  mysql:
    image: mysql:8.0
    volumes:
      - ../data/mysql:/var/lib/mysql
    expose:
      - 3306
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASES}
    restart: always
    cap_add: [ SYS_NICE ]
    command: --disable-log-bin
  redis:
    image: redis:5
    expose:
    - 6379
    ports:
      - "${REDIS_PORT}:3306"
    volumes:
      - ../data/redis:/data
    restart: always

  phpmyadmin:
   image: phpmyadmin/phpmyadmin
   ports:
      - "${PHPMYADMIN_PORT}:80"
   depends_on:
      - mysql
   environment:
   - PMA_HOST=mysql
   restart: always

networks:
  default:
    external:
      name: ${USER_NETWORK}

