version: '3'

services:
  nginx:
    build:
      context: './nginx'
    volumes:
      - ${WEB_ROOT}:/var/www/html
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    restart: always
  mysql:
    build:
      context: './mysql'
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  php-cli:
    build:
      context: './php-cli'
    volumes:
      - ${WEB_ROOT}:/var/www/html
    expose:
      - "9000"
    ports:
      - "23461:23460"
    depends_on:
      - mysql
      - redis
    tty: true
    restart: always

  php-fpm:
    build:
      context: './php-fpm'
    volumes:
      - ${WEB_ROOT}:/var/www/html
    expose:
      - "9000"
    depends_on:
      - mysql
      - redis
    restart: always
    stdin_open: true
    tty: true
    cap_add:
      - ALL

  redis:
    build:
      context: './redis'
    volumes:
      - ../data/redis:/data
    restart: always

  phpmyadmin:
    build:
      context: './phpmyadmin'

volumes:
  mysql_data:
networks:
  default:
    external:
      name: ${USER_NETWORK}
